
//------------- CREATE DATABASE ---------------------------
// https://docs.snowflake.com/ja/sql-reference/sql/create-database.html
// TRANSIENTを指定するとFiale-Safeが無効になるためTimeTravel期間を超えるとリカバリ不可
USE ROLE SYSADMIN;
CREATE TRANSIENT DATABASE IF NOT EXISTS TEST_DB
    DATA_RETENTION_TIME_IN_DAYS = 1
    MAX_DATA_EXTENSION_TIME_IN_DAYS = 1
//  DEFAULT_DDL_COLLATION = 'utf8'
;

-- TableへのALL権限付与
GRANT USAGE ON DATABASE TEST_DB TO ROLE BASE_ROLE;
GRANT USAGE ON SCHEMA TEST_SCHEMA TO ROLE BASE_ROLE;
GRANT ALL ON DATABASE TATENO_TEST_DB TO ROLE BASE_ROLE; // テーブルへの権限
GRANT ALL ON FUTURE SCHEMA IN DATABASE TEST_DB to ROLE BASE_ROLE;

-- DatabaseオブジェクトのOwnership変更
USE ROLE SYSADMIN;
GRANT OWNERSHIP ON DATABASE TO ROLE BASE_ROLE;

-- DatabaseオブジェクトのOwnership変更（現在の権限設定を全て削除）
USE ROLE SYSADMIN;
GRANT OWNERSHIP ON DATABASE TEST_DB TO ROLE BASE_ROLE REVOKE CURRENT GRANTS;

