USE ROLE SYSADMIN;
CREATE OR REPLACE WAREHOUSE WH_XSMALL WITH
warehouse_size='XSMALL'
MAX_CLUSTER_COUNT=2
MIN_CLUSTER_COUNT=1
SCALING_POLICY=ECONOMY
AUTO_SUSPEND=60
AUTO_RESUME=TRUE
INITIALLY_SUSPENDED=TRUE
RESOURCE_MONITOR='MONTHLY_WH_XSMALL_MAX'
;

----- RoleへWH利用権限の付与/除去 ---------------------
USE ROLE SYSADMIN;
GRANT ALL ON WAREHOUSE WH_XSMALL TO ROLE COMPUTE_ROLE;
GRANT ALL ON WAREHOUSE WH_XSMALL TO ROLE SECURITY_ROLE;

REVOKE ALL ON WAREHOUSE <wh name> FROM ROLE <role name>; 