AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  TemplateS3BucketName:
    Type: String
  TemplatePath:
    Type: String
    Default: "https://<s3-bucketname>.s3.ap-northeast-1.amazonaws.com/test"
  KeyName:
    Type: String
  ScpS3Bucket:
    Type: String
  SshLocation:
    Description: Access IP from home
    Type: String
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: "must be a CIDR block"
  WinInstanceType:
    Type: String
    Default: t3a.medium
  WinInstanceImageId:
    Type: String
    Default: ami-0890484998c6a6e77
  RedshiftVpcCidrBlock: 
    Type: String
  RedshiftSubnetCidrBlock:
    Type: String
  SrcVpcId:
    Type: String
  SrcVpcCidrBlock:
    Type: String
  SrcRouteTableId:
    Type: String

Resources:
  InfraBaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${TemplateS3BucketName}.s3.ap-northeast-1.amazonaws.com/infra.yaml'
      TimeoutInMinutes: 60
      Parameters:
        S3BucketForSCP: !Ref ScpS3Bucket
        RedshiftVpcCidrBlock: !Ref RedshiftVpcCidrBlock
        RedshiftSubnetCidrBlock: !Ref RedshiftSubnetCidrBlock
        
  VPCPeeringStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${TemplateS3BucketName}.s3.ap-northeast-1.amazonaws.com/vpcpeering.yaml'
      TimeoutInMinutes: 60
      Parameters:
        PeerVpcId: !GetAtt InfraBaseStack.Outputs.RedshiftVpcId
        VpcId: !Ref SrcVpcId
        ScpRouteTableId: !Ref SrcRouteTableId
        RedshiftRouteTableId: !GetAtt InfraBaseStack.Outputs.RedshiftRouteTableId
        VpcCidrBlock: !Ref SrcVpcCidrBlock
        PeerVpcCidrBlock: !Ref RedshiftVpcCidrBlock

  ScpToolInstanceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${TemplateS3BucketName}.s3.ap-northeast-1.amazonaws.com/scp-tool.yaml'
      TimeoutInMinutes: 60
      Parameters:
        KeyName: !Ref KeyNameC:\Users\tateno.rika\dev\cloudformation\vertica\infra.yaml
        WinInstanceImageId: !Ref WinInstanceImageId
        VpcId: !Ref VerticaVpcId
        SubnetId: !Ref VerticaSubnetId
        SSHLocation: !Ref SshLocation 
        WinInstanceType: !Ref WinInstanceType

  