USE ROLE ACCOUNTADMIN;
SHOW NETWORK POLICIES;
SHOW SHARES;

SHOW ROLES;
-- ACCOUNTADMINで実行した場合は全ROLE（Databaseに関わらない）が表示される
SELECT * FROM <DB_NAME>.INFORMATION_SCHEMA.APPLICABLE_ROLES;

-------------
-- grants
-- https://docs.snowflake.com/en/sql-reference/sql/show-grants.html
-------------
SHOW GRANTS;
SHOW GRANTS ON ACCOUNT -- account level privileges
SHOW GRANTS TO ROLE <role_name>
SHOW GRANTS TO USER <user_name> -- ユーザに紐づくROLE一覧

SHOW USERS;

SHOW WAREHOUSES;
SHOW DATABASES;
SHOW INTEGRATIONS;
SHOW SESSION POLICIES;

-- database type objects
SHOW SCHEMAS;
SHOW OBJECTS;
SHOW TABLES;
SHOW EXTERNAL TABLES;
SHOW VIEWS;
SHOW MATERIALIZED VIEWS;
SHOW MASKING POLICIES;
SHOW ROW ACCESS POLICIES;
SHOW COLUMNS;
SHOW FILE FORMATS;
SHOW SEQUENCES;
SHOW STAGES;
SHOW TAGS;
SHOW PIPES;
SHOW STREAMS;
SHOW TASKS;
SHOW USER FUNCTIONS;
SHOW EXTERNAL FUNCTIONS;
SHOW PROCEDURES;